dataset:
  num_patients: 2000 # Like, actual people, not data points
  output_filename: "patient_data"
  export_format: "csv"

patient_attributes:
  age_range: [20, 80]
  hba1c_level_range: [5.5, 12.0]
  glucose_hyper_range_mmol_l: [10.0, 20.0]
  glucose_hypo_range_mmol_l: [3.0, 5.0]
  diabetes_types: ["Type 1", "Type 2", "Gestational"]
  
data_generation:
  past_days_to_simulate: 7
  hyper_event_probability: 0.3
  hypo_event_probability: 0.2
  updates_per_cycle: 20
  update_interval_seconds: 5
